production:
  adapter: postgresql
  encoding: utf8
  database: dashboard_db
  username: postgres
  password: '123456'
  host: localhost
development:
  adapter: postgresql
  encoding: utf8
  database: dashboard_db
  username: postgres
  password: '123456'
  host: localhost

